### ISSUE TITLE
Affect tracking in status_affect.lua

### ISSUE THREAD

**Issue by kerchunkwow** [kerchunkwow/kermudlet#1]
`status_affect.lua` is a work in progress module for tracking and reporting on magical affects like Sanctuary. The current implementation is preliminary to the point of being non-functional.

The requirements for this module are:

- [ ]  Implement robust apply/remove functionality to set/unset the status of all buffs by identifying the messages associated with each. This will require a new event/handler pathway since these messages will only appear on the profile of the affected character(s).
- [ ] Create an enhanced version of the `aff` command useable from the Main Session that reports the `aff` status of everyone in the party with useful highlighting (e.g., greater than half duration, less than half duration, 0-1 ticks remaining).
- [ ] Integrate affect status with the Party Console to add images or emojis indicating which spells are affecting which players. Ideally, an interactive label element that allows missing buffs to be recast with clicks. Expiring buffs could flash or change color.
- [ ] Ensure affects are initialized at login.
- [ ] Permit easy querying of status effects from script (i.e., `pcStatus[4]['Sanctuary']`) to facilitate the implementation of smart rebuff routines that could automatically replace key missing buffs.
